### ISSUE TITLE
Misleading README.md file

### ISSUE THREAD

**Issue by ck-pgtrebacz** [TomaszTrebacz/fox.CMS#1]
You did not write a documentation of your project. It's the first impression and introduction to the work you have done. 

Impacts all Readme.md files in your repo.

Reference [Awesome Readme](https://github.com/matiassingers/awesome-readme/blob/master/readme.md) and [Readme Driven Development](https://tom.preston-werner.com/2010/08/23/readme-driven-development.html).

**Comment by TomaszTrebacz** [comment]
Added Readme.md in each repository.
