### ISSUE TITLE
No tests in modules

### ISSUE THREAD

**Issue by ck-pgtrebacz** [TomaszTrebacz/fox.CMS#2]
Modules does not have Unit/Integration/E2E tests.

Impacts all modules.

All code should be covered on edge cases to ensure that it works as intended. You can bootstrap yourself using [Introduction to TDD with Jest](https://www.freecodecamp.org/news/a-quick-introduction-to-test-driven-development-with-jest-cac71cb94e50/)

**Comment by TomaszTrebacz** [comment]
Writed unit/integration/e2e tests on backend.
